//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_schet { get; set; }
        public int ID_administrator { get; set; }
        public int ID_type_pay { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Schet Schet { get; set; }
        public virtual Type_pay Type_pay { get; set; }
    }
}
