//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphic
    {
        public int ID { get; set; }
        public int ID_mechanic { get; set; }
        public int ID_zapis { get; set; }
    
        public virtual Mechanic Mechanic { get; set; }
        public virtual Zapic Zapic { get; set; }
    }
}
