//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schet()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_akt { get; set; }
        public int ID_zapchast { get; set; }
        public int ID_client { get; set; }
    
        public virtual Akt Akt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
        public virtual Client Client { get; set; }
        public virtual Zapchast Zapchast { get; set; }
    }
}
