//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Station.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ID { get; set; }
        public System.DateTime Date_output { get; set; }
        public System.DateTime Date_input { get; set; }
        public int Count { get; set; }
        public int ID_zapchast { get; set; }
    
        public virtual Zapchast Zapchast { get; set; }
    }
}
